### ISSUE TITLE
Further document the `-e` option

### ISSUE THREAD

**Issue by ngirard** [GarkGarcia/icon-pie#11]
An explanation is missing on what to provide to `-e`.

Also, one example seems to imply that `-e` can be given multiple times, but it's documented nowhere and the reason why is not given.

**Comment by GarkGarcia** [comment]
Yes, `-e` can be given multiple time. The reason why is because that allows you to control which image to use in the creation of each entry.

I'll make sure to include detailed examples.

**Comment by GarkGarcia** [comment]
Partially fixed on https://github.com/GarkGarcia/icon-pie/commit/30d46e701eed0635d00cf58779218ce1a0a00147. @ngirard What do you think about the examples?

Fell free to rephrase them to improve readability.

**Comment by ngirard** [comment]
I think that's nice !

I just found it unusual to read "IconPie, do such and such". How about simply "Do such and such" ?

Also, I guess the command line should read `-png icon.tar` in the last example.

**Comment by GarkGarcia** [comment]
Yep, it's `-png icon.tar`. Done!

Should we consider this issue closed then? I'm not sure there's enough information there for a newcomer.

**Comment by ngirard** [comment]
Yes, I think for now it's just fine !
