### ISSUE TITLE
IconPie's SVG renderer(s)

### ISSUE THREAD

**Issue by ngirard** [GarkGarcia/icon-pie#15]
@GarkGarcia, did you consider using [resvg](https://github.com/RazrFalcon/resvg) or GNOME's [librsvg](https://github.com/GNOME/librsvg) ?

**Comment by GarkGarcia** [comment]
I'm considering `resvg`, but as far as I can tell it targets nightly, which would impose an unnecessary limitation to `icon_baker`.

**Comment by GarkGarcia** [comment]
Maybe switching to `cairo` altogether is a good idea.

**Comment by GarkGarcia** [comment]
@ngirard I'm working on porting the `svg` functionalities to `resvg`. Check out https://github.com/GarkGarcia/icon_baker/issues/3.

**Comment by GarkGarcia** [comment]
Fixing this will largely improve `svg` support, as you can imagine.

**Comment by ngirard** [comment]
Hey @GarkGarcia, now, that's great news ! I think you made the right choice: apparently resvg is [the most accurate standalone SVG renderer nowadays](https://www.reddit.com/r/rust/comments/c2m8t7/resvg_07_an_svg_rendering_library/erl9ffw/).

On my side, I kept investigating on the icon themes thing ; I'm starting to get a clearer picture, I will commit the changes to the wiki page tomorrow (it's quite late here in France).

Thanks for the heads up !

**Comment by GarkGarcia** [comment]
**IconPie** now supports _[Static SVG Full 1.1](https://github.com/RazrFalcon/resvg#svg-support)_ ❤️
