### ISSUE TITLE
Doc: mention that the rasterizing of SVG files done with antialiasing

### ISSUE THREAD

**Issue by ngirard** [GarkGarcia/icon-pie#17]
Title says it all.

Would be nice to mention it in the README.

**Comment by GarkGarcia** [comment]
I believe so, that authors of [`nsvg`](https://crates.io/crates/nsvg) don't specify it.

**Comment by ngirard** [comment]
I'm not sure we're done here.

I read from discussions between icon creators that this point seemed to matter, so I think the documentation should make it clear.

If we're unsure about whan `nsvg` does, we can always ask upstream. Would you like me to do so ?

**Comment by GarkGarcia** [comment]
That would be great!

**Comment by ngirard** [comment]
[Done](https://github.com/nickbrowne/nsvg/issues/3).

**Comment by GarkGarcia** [comment]
I'm working on porting the app's `svg` functionalities to `resvg`, which does use antialiasing as far as I can tell. Check out https://github.com/GarkGarcia/icon_baker/issues/3.

**Comment by ngirard** [comment]
Nice !

Meanwhile, nsvg's author [confirmed](https://github.com/nickbrowne/nsvg/issues/3#issuecomment-526989622) anti-aliasing is on, so we can add it to the README.

**Comment by GarkGarcia** [comment]
Fixed on https://github.com/GarkGarcia/icon-pie/commit/a64380a1c6fa490db672a06cefdee62e921a1516.
