### ISSUE TITLE
Unsure about the background color of the generated icons

### ISSUE THREAD

**Issue by ngirard** [GarkGarcia/icon-pie#6]
The documentation currently says nothing about the background color of the generated icons, especially using transparent PNGs or SVG images.

Perhaps it would be useful to add some clarifications, or even provide a `--background-color` option ?

**Comment by GarkGarcia** [comment]
The background is always kept transparent. I'll make sure to mention this in the README.

**Comment by GarkGarcia** [comment]
Fixed on https://github.com/GarkGarcia/icon-pie/commit/f3bc744ff67cb305ec83dc8d3293bb404680b6b5.
