### ISSUE TITLE
Add favicon support

### ISSUE THREAD

**Issue by ngirard** [GarkGarcia/icon-pie#8]
Along with generating application icons, a common need is to produce favicons ; and you already have all it gets to provide such a feature.

How about adding it ?

For what is worth, here are some existing favicon generators:

**Command-line generators**
- [favicon_maker](https://github.com/at1as/favicon_maker), written in Rust ;
- FaviconBuild (Shell script; last updated: 2015; [project page](https://theknowledgeaccelerator.com/faviconbuild/), [repo](https://github.com/matthewsanders/faviconbuild))
- [Imagemagick](http://www.imagemagick.org/Usage/thumbnails/#favicon) the *de facto* command-line image manipulation toolkit, can also be used to generate favicons

**Online generators**
- https://www.favicon-generator.org
- https://realfavicongenerator.net/

**Comment by GarkGarcia** [comment]
Yep, `favicons` should definitively be a part of this app. I guess we have a similar problem to https://github.com/GarkGarcia/icon-pie/issues/7#issuecomment-526922072: in the current scheme there wouldn't be a way to specify which source to use for each platform.

How would you like this feature to work (from the user's perspective)?

**Comment by GarkGarcia** [comment]
Also, this seems like a feature to implemented in [`icon_baker`](https://github.com/GarkGarcia/icon_baker). Feel free to create an issue with a feature request there too.

**Comment by ngirard** [comment]
Alright, so after drowning in an ocean of outdated and convoluted information, I'd suggest: using [this answer](https://stackoverflow.com/a/48646940/3050893) as a reference, and then, when in "favicon mode":

1. checking the input image has transparency, and failing with an error message otherwise (favicons need to have a transparent background);
2. generating a single 196x196 png image, and
3. optionally generating such helper html code as
```html
<link rel="shortcut icon" type="image/png" href="/img/icon-196x196.png">
<link rel="shortcut icon" sizes="196x196" href="/img/icon-196x196.png">
<link rel="apple-touch-icon" href="/img/icon-196x196.png">
```

**Comment by GarkGarcia** [comment]
I think we should always include the html helper, just to keep the interface clean.

Also, we should allow the user to specify which sizes to include. So ideally we'd simply add an `-fav` or `-favicon` output option and keep doing everything working as is.

Our main issue is, other icon formats allow for multiple icons with the same size, so the current interface allows that too. However, we can't specify multiple entries with the same size in the favicon use case (the browser simply won't know each one to use).

We could return an error, but that would require adding an extra variant to [`icon_baker::Error`](https://docs.rs/icon_baker/2.2.0/icon_baker/enum.Error.html), which would get propagated to the other icon formats. This is, in my opinion, the only thing we got to sort out before implementing this feature.

**Comment by GarkGarcia** [comment]
Maybe disallowing multiple etries with a common resolution is a wise choice. You generally don't want that when you can't control the name or the color deapth of the outputed entries.

**Comment by ngirard** [comment]
> We could return an error, (...)

Or, use [clap](https://docs.rs/clap/2.33.0/clap/) for argument parsing, which allows for involved scenarios painlessly, by e.g. offering subcommands...

**Comment by ngirard** [comment]
Found another favicon generator in shell script. I'm adding it to the list in my 1st message.

**Comment by GarkGarcia** [comment]
> 
> 
> > We could return an error, (...)
> 
> Or, use [clap](https://docs.rs/clap/2.33.0/clap/) for argument parsing, which allows for involved scenarios painlessly, by e.g. offering subcommands...

Introducing a subcommand would increase complexity, which I don't fancy. However, https://github.com/GarkGarcia/icon-pie/issues/14 hints that maybe the introduction of something like this can help with more complex workflows.

I think we should think about implementing something that gives the user control over how entries are named on `-png` and `-favicon` output.

On regards to the `clap`, I'd like to still parse the user input myself. It's the funniest part. 😋

**Comment by GarkGarcia** [comment]
It would be great to hear some feedback from potential users in https://github.com/GarkGarcia/icon-pie/issues/14.

**Comment by GarkGarcia** [comment]
Check out https://github.com/GarkGarcia/icon_baker/issues/4.

**Comment by GarkGarcia** [comment]
@ngirard This is our next priority.

I think we should give the user control over downsampling as we have been giving til now. In other words, we should allow the user to specify which source file and resampling filter to use in each entry.

Currently, there's no mechanism for the user to control how to name each file inside the outputted `.tar` file. This only makes sense for formats that output to a `.tar` file (or any of other `.zip`-like file format for that matter), of course.

However, I think that favicons would benefit greatly from such feature. Our challenge is: how to add this feature in an expressive matter while still maintaining the overall cohesiveness of the general interface.

Any ideas?

**Comment by ngirard** [comment]
Hey @GarkGarcia, kudos for integrating `resvg` to IconPie !

Here are my thoughts about a possible implementation.

How about taking the HTML code as the source of truth for the favicon options ?

IconPie could operate in 2 steps:

1. The first, **optional** step, would consist in generating some default html code, that the user could modify at will. As of 2019 the most reasonable defaults are as mentioned above:
    ```html
    <link rel="shortcut icon" type="image/png" href="/img/icon-196x196.png">
    <link rel="shortcut icon" sizes="196x196" href="/img/icon-196x196.png">
    <link rel="apple-touch-icon" href="/img/icon-196x196.png">
    ```
   If the user already has the appropriate html code, then he uses it directly in step 2

2. In the second step, take a path to an html file as an argument and the name of an image, and produce the icons according to the contents of the html file.

What do you think of this approach ?

**Comment by GarkGarcia** [comment]
Idk. It's pretty reasonable, but I think I deviates a bit from what we've been doing so far.

What about adding a `--name` flag that is required for each entry when outputting to a favicon? For example:
```
$ icon-pie -e icon.png 32 64 128 --name myname -favicon favicon.tar
```

**Comment by ngirard** [comment]
What is the `favicon.tar` in your command-line example ?

**Comment by GarkGarcia** [comment]
It's the outputted `.tar` file, that contains the re-scaled images (such as `/img/icon-196x196.png`, in your example) and a file with the `html` helper.

**Comment by GarkGarcia** [comment]
So, in my example, I would look something like this:
```
/
|-- /img/
|       |-- /img/myname-32x32.png
|       |-- /img/myname-64x64.png
|       |-- /img/myname-128x128.png
|
|-- helper.html

```

**Comment by ngirard** [comment]
Oh. So that would be the output.

So after generating their favicon(s), users would need to untar the archive to the final destination, is that so ?

**Comment by GarkGarcia** [comment]
Yep. I think that would make things more organized, instead of simply dumping everything in the current folder or something. Do you agree?

**Comment by ngirard** [comment]
I'm afraid I'd find it awkward that a command-line favicon generator outputs an archive file that I'd need to extract and delete anyway, just like I'd find it awkward to run `wget` to download some pages, and get an archive file in return.

**Comment by GarkGarcia** [comment]
Alright. So what would be more appropriate? Place the files in the current directory?

**Comment by ngirard** [comment]
Why not directly creating the favicons where IconPie is asked to, like e.g. `icon-pie blah blah -d /path/to/favicons` ?

**Comment by GarkGarcia** [comment]
Makes sense.

On a small about placing the contents of the favicon in a `.tar` file, keep in mind `icon-pie` can output to `stdout`, so you could simply extract it automatically by piping `icon-pie` and `tar`.

**Comment by ngirard** [comment]
Well, do you have any situation in mind where it would be useful to generate an archive with favicons, instead of the favicons themselves ?

**Comment by GarkGarcia** [comment]
One of the features of the app is that it can output to `stdout`. Outputting to directories exclusively would make this impractical.

For the output of the program to be piped to another app it needs to be boxed somehow. The `.tar` file format is just a simple way to do it.

**Comment by ngirard** [comment]
What do you mean by "boxed" ?

Also, I'm having a hard time figuring out how it answers my question. From a user's perspective, when would it be useful to get a tarball when asking for favicons ?

**Comment by GarkGarcia** [comment]
By _boxed_ I mean that the icon needs to be contained in a single byte stream. In other words, it needs to be a single file.

To be honest, there isn't much of clear use case for that, I'd just like to give the user the choice, sinse having this choice adds very little complexity to the interface.

I'd personaly always output to a `.tar` file myself, for instance.

**Comment by GarkGarcia** [comment]
The user wouldn't even have to think about it. If the path they specified is a file, then it outputs a file. If it's directory, then it outputs multiple files in that directory. Seems intuitive for me.

**Comment by GarkGarcia** [comment]
I also have concerns about how would directory-only output be implemented in `icon_baker`. I believe it would greatly limit the library.

**Comment by ngirard** [comment]
> I also have concerns about how would directory-only output be implemented in `icon_baker`. I believe it would greatly limit the library.

I'm confused here...

The discussion is about the behavior of the `icon-pie` binary when asked to generate favicons, not in general. Maybe there are other use cases when creating an archive is useful.

This is not about *removing* a functionality from `IconPie`/`icon_baker`.

Is  `IconPie`/`icon_baker` currently able to output several files at once in the filesystem ?
- If so, where is the limitation you're talking about ?
- If not, then we're talking about *expanding* functionalities, not limiting them.

**Comment by GarkGarcia** [comment]
No, currently neither **IconPie** or `icon_baker` are able to output to several files.

I'm not against implementing it. I'd just like to give the user the choice between outputting to a single `.tar` file or to several files in the filesystem.

Outputing to a single file is useful, even in the favicon case, because it allows for piping. The user can pipe the output from `icon-pie` to another program without writing it to a file.

**Comment by ngirard** [comment]
Alright.

The [mini_fs](https://docs.rs/mini-fs/0.2.2/mini_fs/) crate might be useful here. What to you think ?

**Comment by GarkGarcia** [comment]
Yeah it seems useful! So now we need to figure out how are we going to implement this in `icon_baker`.

**Comment by ngirard** [comment]
Well I guess you might now better ! Otherwise I can dedicate some time to it tomorrow if you want.

**Comment by GarkGarcia** [comment]
Fixed at https://github.com/GarkGarcia/icon-pie/commit/6ec0e535662407808d548f5aad80a086ccbc0650.
